// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class StringHolder
{
        public const string achievement_buy_your_first_ship = "CgkI3eXNjrQcEAIQHQ"; // <GPGSID>
        public const string achievement_flash = "CgkI3eXNjrQcEAIQCQ"; // <GPGSID>
        public const string achievement_stars = "CgkI3eXNjrQcEAIQGw"; // <GPGSID>
        public const string achievement_buy_all_ships = "CgkI3eXNjrQcEAIQHg"; // <GPGSID>
        public const string achievement_aliens = "CgkI3eXNjrQcEAIQAg"; // <GPGSID>
        public const string achievement_destroyer_3 = "CgkI3eXNjrQcEAIQEg"; // <GPGSID>
        public const string achievement_destroyer_4 = "CgkI3eXNjrQcEAIQEw"; // <GPGSID>
        public const string achievement_destroyer_5 = "CgkI3eXNjrQcEAIQFA"; // <GPGSID>
        public const string achievement_speedster = "CgkI3eXNjrQcEAIQCA"; // <GPGSID>
        public const string leaderboard_highest_speed_reached = "CgkI3eXNjrQcEAIQAA"; // <GPGSID>
        public const string achievement_stars_2 = "CgkI3eXNjrQcEAIQHA"; // <GPGSID>
        public const string achievement_super_sonic = "CgkI3eXNjrQcEAIQCg"; // <GPGSID>
        public const string achievement_logged_on_successfully = "CgkI3eXNjrQcEAIQGg"; // <GPGSID>
        public const string achievement_tutorial_complete = "CgkI3eXNjrQcEAIQBw"; // <GPGSID>
        public const string achievement_death_2 = "CgkI3eXNjrQcEAIQFg"; // <GPGSID>
        public const string achievement_death_3 = "CgkI3eXNjrQcEAIQFw"; // <GPGSID>
        public const string achievement_death_4 = "CgkI3eXNjrQcEAIQGA"; // <GPGSID>
        public const string achievement_death_5 = "CgkI3eXNjrQcEAIQGQ"; // <GPGSID>
        public const string achievement_you_have_unlocked_the_secret_ship = "CgkI3eXNjrQcEAIQHw"; // <GPGSID>
        public const string achievement_first_death = "CgkI3eXNjrQcEAIQCw"; // <GPGSID>
        public const string achievement_correct_pause = "CgkI3eXNjrQcEAIQDQ"; // <GPGSID>
        public const string achievement_paused = "CgkI3eXNjrQcEAIQDA"; // <GPGSID>
        public const string achievement_destroyer = "CgkI3eXNjrQcEAIQBA"; // <GPGSID>
        public const string achievement_aliens_2 = "CgkI3eXNjrQcEAIQAw"; // <GPGSID>
        public const string achievement_aliens_3 = "CgkI3eXNjrQcEAIQDw"; // <GPGSID>
        public const string achievement_aliens_4 = "CgkI3eXNjrQcEAIQEA"; // <GPGSID>
        public const string achievement_aliens_5 = "CgkI3eXNjrQcEAIQEQ"; // <GPGSID>
        public const string achievement_aliens_6 = "CgkI3eXNjrQcEAIQFQ"; // <GPGSID>
        public const string achievement_destroy_2 = "CgkI3eXNjrQcEAIQBQ"; // <GPGSID>

}

